### ISSUE TITLE
Rakefile not working

### ISSUE THREAD

**Issue by rafaelsaback** [Brazilian-Institute-of-Robotics/bundles-flat_fish#11]
My rock is getting some error while compiling the bundles/flat_fish. I'm having the following error:

Warning: Could not find plugin to read objects from file "models/sdf/oil_rig_manifold/visual.dae".
Error no data loaded.
rake aborted!
cannot convert models/sdf/oil_rig_manifold/visual.dae to the osgb format
/home/rafaelsaback/flatfish/rock/bundles/flat_fish/Rakefile:13:in `block (2 levels) in <top (required)>'
Tasks: TOP => default => models/sdf/oil_rig_manifold/visual.dae.osgb

**Comment by doudou** [comment]
Do you build all bir.flat_fish ? It seems that you are missing the OSG plugin. Verify that it is present in lib/osgPlugins-* (file name is osgdb_dae.so). And if it is present, check that the full path to the osgPlugins directory is in OSG_LIBRARY_PATH

If the directory is NOT in OSG_LIBRARY_PATH, try https://github.com/Brazilian-Institute-of-Robotics/bir.flat_fish-package_set/pull/19

**Comment by rafaelsaback** [comment]
Well, @gustavoneves12 has helped me solving the problem. Basically, the package collada_dom (and consequently collada_osg also) was breaking because there was some conflict between the minizip intalled in my pc and the internal minizip inside the collada_dom. Gustavo has deleted all the modules related to minizip in my computer, so now everything is fine.
